---
title: "Untitled"
author: "young-robertson"
date: "2/18/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf)
library(ggplot2)
library(scales)
library(ggmap)
library(dplyr)

```


```{r}
ak_regions <- read_sf("shapefiles/ak_regions_simp.shp")

head(ak_regions)
class(ak_regions)  #sf type of dataframe, gives it features specific to geospatial vector data
plot(ak_regions)  #quick plot for each column in the table except geometry column
st_crs(ak_regions)  #coordinate ref system

```

```{r}
ak_regions_3338 <- ak_regions %>% 
  st_transform(crs = 3338)   #this is a better coordinate system for Alaska

plot(ak_regions_3338)

ak_regions_3338 %>% 
  select(region)

```

```{r}
pop <- read.csv("shapefiles/alaska_population.csv")

head(pop)


#calculate total population by region (group by geometry)
#do a spatial join

class(pop)  #pop is a dataframe

```

```{r}
pop_4326 <- pop %>% 
  st_as_sf(coords = c("lng" , "lat"), 
          crs =  4326,
          remove = FALSE)  #which columns are the x and y coords, which coordinate system we're in (crs) WGS84 is a good guess (crs = 4326) have to read in the data in the project it's already in and THEN transform it (st_transform)

head(pop_4326)
class(pop_4326)  #dataframe

#but the two I want to join are diff coordinate types, so have to change the population data to a type that can be merged with the geometry data
pop_3338 <- pop_4326 %>% 
  st_transform(crs = 3338)

pop_joined <- st_join(pop_3338, ak_regions_3338 , join = st_within)
head(pop_joined)  #now have region column in order to do summary calcs
```

```{r}
pop_region <- pop_joined %>% 
  as.data.frame()   %>%            #change from sf object to dataframe
  group_by(region) %>%    #group by region
  summarise(total_pop = sum(population))  #calculate the sum of population by region
  
head(pop_region)

pop_region_3338 <- left_join(ak_regions_3338 , pop_region , by="region")

plot(pop_region_3338)
```

```{r}
pop_mgmt_3338 <- pop_region_3338 %>% 
  group_by(mgmt_area) %>% 
  summarise(total_pop = sum(total_pop) , do_union = FALSE)

plot(pop_mgmt_3338)
```

## Making Maps

```{r}
rivers_3338 <- read_sf("shapefiles/ak_rivers_simp.shp")
```


```{r}
ggplot() +
  geom_sf(data = pop_region_3338, mapping = aes(fill = total_pop))+
  geom_sf(data = rivers_3338, mapping = aes(size = StrOrder)) +
  geom_sf(data = pop_3338 , mapping = aes()) +
  scale_size(range = c(0.01, 0.2), guide = "none") +
  theme_bw() +
  labs(fill = "Total Population") +
  scale_fill_continuous(low = "khaki" , high = "firebrick" , labels = comma)

```

```{r}
pop_3857 <- pop_3338 %>%
  st_transform(crs = 3857)

# Define a function to fix the bbox to be in EPSG:3857
# See https://github.com/dkahle/ggmap/issues/160#issuecomment-397055208
ggmap_bbox_to_3857 <- function(map) {
  if (!inherits(map, "ggmap")) stop("map must be a ggmap object")
  # Extract the bounding box (in lat/lon) from the ggmap to a numeric vector, 
  # and set the names to what sf::st_bbox expects:
  map_bbox <- setNames(unlist(attr(map, "bb")), 
                       c("ymin", "xmin", "ymax", "xmax"))
  
  # Coonvert the bbox to an sf polygon, transform it to 3857, 
  # and convert back to a bbox (convoluted, but it works)
  bbox_3857 <- st_bbox(st_transform(st_as_sfc(st_bbox(map_bbox, crs = 4326)), 3857))
  
  # Overwrite the bbox of the ggmap object with the transformed coordinates 
  attr(map, "bb")$ll.lat <- bbox_3857["ymin"]
  attr(map, "bb")$ll.lon <- bbox_3857["xmin"]
  attr(map, "bb")$ur.lat <- bbox_3857["ymax"]
  attr(map, "bb")$ur.lon <- bbox_3857["xmax"]
  map
}


bbox <- c(-170, 52, -130, 64)   # This is roughly southern Alaska
ak_map <- get_stamenmap(bbox, zoom = 4)
ak_map_3857 <- ggmap_bbox_to_3857(ak_map)

ggmap(ak_map_3857) + 
  geom_sf(data = pop_3857, aes(color = population), inherit.aes = F) +
  scale_color_continuous(low = "khaki", high =  "firebrick", labels = comma)

ggmap(ak_map_3857) + 
  geom_sf(data = pop_3857, aes(color = population), inherit.aes = FALSE) +
  scale_color_continuous(low = "khaki" , high = "firebrick" , labels = comma)
```

